apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
  namespace: oracle-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: user-service
  type: LoadBalancer